# Generated by Django 5.1.1 on 2025-05-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_order_payment_details_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pidx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
