# Generated by Django 5.1.1 on 2025-05-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_order_pidx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pidx',
        ),
    ]
